language: cpp
os: linux
dist: xenial

matrix:
  include:
    - env: BUILD_TYPE="nocomm-omp"
    - env: BUILD_TYPE="nocomm-ser"
    - env: BUILD_TYPE="nocomm-omp-reduce"
    - env: BUILD_TYPE="nocomm-ser-reduce"
    - env: BUILD_TYPE="mpi-pure"
    - env: BUILD_TYPE="mpi-omp"
    - env: BUILD_TYPE="mpi-allreduce-omp"
    - env: BUILD_TYPE="mpi-bcast-omp"
    - env: BUILD_TYPE="mpi-put-omp"

env:
  global:
    - MAKEFLAGS="-j 2"
    - OMPI_MCA_btl=tcp,self

addons:
  apt:
    sources:
    - sourceline: 'ppa:lkoppel/robotics'
    packages:
      - libblas-dev
      - liblapack-dev
      - liblapacke-dev
      - libopenmpi-dev
      - openmpi-bin
      - libeigen3-dev

script:
    - cd "${TRAVIS_BUILD_DIR}"
    - cd build/makefiles/${BUILD_TYPE}
    - make
    - make test
