language: cpp
os: linux
dist: focal

addons:
    packages:
      - libblas-dev
      - liblapack-dev
      - liblapacke-dev
      - libopenmpi-dev
      - libeigen3-dev

script:
    - cd build 
    - make 
    - ./bpmf -i 10 -n ../data/movielens/ml-train.mtx -p ../data/movielens/ml-test.mtx
