language: cpp
os: linux
dist: xenial

matrix:
  include:
    - env: CMAKE_FLAGS="-DBPMF_COMM=NO_COMM -DENABLE_OPENMP=OFF -DENABLE_REDUCE=OFF"
    - env: CMAKE_FLAGS="-DBPMF_COMM=NO_COMM -DENABLE_OPENMP=ON -DENABLE_REDUCE=OFF"
    - env: CMAKE_FLAGS="-DBPMF_COMM=NO_COMM -DENABLE_OPENMP=OFF -DENABLE_REDUCE=ON"
    - env: CMAKE_FLAGS="-DBPMF_COMM=NO_COMM -DENABLE_OPENMP=ON -DENABLE_REDUCE=ON"

    - env: CMAKE_FLAGS="-DBPMF_COMM=MPI_ISEND_COMM -DENABLE_OPENMP=OFF -DENABLE_REDUCE=OFF"
    - env: CMAKE_FLAGS="-DBPMF_COMM=MPI_ISEND_COMM -DENABLE_OPENMP=ON -DENABLE_REDUCE=OFF"

    - env: CMAKE_FLAGS="-DBPMF_COMM=MPI_BCAST_COMM -DENABLE_OPENMP=OFF -DENABLE_REDUCE=OFF"
    - env: CMAKE_FLAGS="-DBPMF_COMM=MPI_BCAST_COMM -DENABLE_OPENMP=ON -DENABLE_REDUCE=OFF"

env:
  global:
    - OMPI_MCA_btl=tcp,self

addons:
  apt:
    sources:
    - sourceline: 'ppa:lkoppel/robotics'
    packages:
      - libblas-dev
      - liblapack-dev
      - liblapacke-dev
      - libopenmpi-dev
      - openmpi-bin
      - libeigen3-dev

script:
    - cd "${TRAVIS_BUILD_DIR}"
    - mkdir build && cd build 
    - cmake .. $CMAKE_FLAGS
    - make VERBOSE=1
    - ctest -VV
