pipeline {
    agent {
        dockerfile {
            dir 'ci'
        }
    }
    stages {
        stage('Test') {
            steps {
                sh 'git --version'
                sh 'gcc --version'
                sh 'g++ --version'
                sh 'cmake --version'
                sh 'gfortran --version'
                sh 'python3 --version'
                sh 'mpiexec --version'
            }
        }
    }
}
