name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OMPI_MCA_btl: tcp,self
    strategy:
      matrix:
        flags: 
          - "-DBPMF_COMM=NO_COMM -DENABLE_OPENMP=OFF -DENABLE_REDUCE=OFF"
          - "-DBPMF_COMM=NO_COMM -DENABLE_OPENMP=ON -DENABLE_REDUCE=OFF"
          - "-DBPMF_COMM=NO_COMM -DENABLE_OPENMP=OFF -DENABLE_REDUCE=ON"
          - "-DBPMF_COMM=NO_COMM -DENABLE_OPENMP=ON -DENABLE_REDUCE=ON"
          - "-DBPMF_COMM=MPI_ISEND_COMM -DENABLE_OPENMP=OFF -DENABLE_REDUCE=OFF"
          - "-DBPMF_COMM=MPI_ISEND_COMM -DENABLE_OPENMP=ON -DENABLE_REDUCE=OFF"
          - "-DBPMF_COMM=MPI_BCAST_COMM -DENABLE_OPENMP=OFF -DENABLE_REDUCE=OFF"
          - "-DBPMF_COMM=MPI_BCAST_COMM -DENABLE_OPENMP=ON -DENABLE_REDUCE=OFF"

    steps:
    - uses: actions/checkout@v2

    - name: Install needed packages
      run: |
        sudo apt-get update
        sudo apt install -y cmake libblas-dev liblapack-dev liblapacke-dev libopenmpi-dev openmpi-bin libeigen3-dev librandom123-dev

    - name: Configure OpenMPI
      run: |
        openmpi_mca_params=$HOME/.openmpi/mca-params.conf
        mkdir -p $(dirname $openmpi_mca_params)
        echo plm=isolated >> $openmpi_mca_params
        echo rmaps_base_oversubscribe=true >> $openmpi_mca_params
        echo btl_base_warn_component_unused=false >> $openmpi_mca_params
        echo btl_vader_single_copy_mechanism=none >> $openmpi_mca_params

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DRANDOM123_INCLUDE_DIRS=/usr/include -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{matrix.flags}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -V -C ${{env.BUILD_TYPE}}
      
